### PR TITLE
fixes for various UI tickets

### PR DESCRIPTION
**Pull request by hstove**
Includes fixes for: #101, #93, #80, #103, #91, #94, #92

You can preview this PR here: https://stacks-explorer.herokuapp.com/

### CODE REVIEW

**Comment by hstove** [comment]
@markmhx sorry this took longer than expected to spin up for testing - I'm adding you here as most of these are just visual tweaks that you've requested.

**Comment by hstove** [comment]
Also includes #75

**Comment by hstove** [comment]
I'm closing this, because the code is in #114

**Comment by timstackblock** [comment]
101 is the only thing that still needs to be done

**Pull request closed without merging**
