### PR TITLE
New tests for using search

### PR DESCRIPTION
**Pull request by timstackblock**

### CODE REVIEW

**Comment by timstackblock** [comment]
Hank these failures are because the local app is not working on circleCI, the test work locally I thought it might have been an issue with the elements changing but everything is ok locally. 

download (1)

**Comment by timstackblock** [comment]
@hstove please merge this branch into your branch. This branch takes a screen shot of the failed test this is how I got the screen shot above that showed me the local app was broken. I looked at the test results for your PR and the the local app still seems broken.

**Comment by timstackblock** [comment]
Local app is still broken in CI the test takes a screen shot of the home page its still giving the image seen above.

**Comment by hstove** [comment]
I let Tim know already, but I finally figured out what was going on with CircleCI. It was some stupid thing where they would stop processes if you moved onto the next "step", which isn't how it worked in the past (when we set this up). Anyways, finally Tim can be unblocked here.

**Comment by timstackblock** [comment]
Thanks Hank

**Pull request merged**
